[package]
name = "wakavis"
version = "0.1.0"
authors = ["Matthew Gleich <email@mattglei.ch>"]
edition = "2018"

[dependencies]
# anyhow is an awesome crate for error handling; it basically takes care of all
# errors that implement std's std::error::Error
anyhow = "1.0.34"
dirs = "3.0.1"
